### ISSUE TITLE
How to change Units or Measure

### ISSUE THREAD

**Issue by JonElster** [mark-rolich/RulersGuides.js#14]
Very cool...
thx

Any idea how I can change the units of measure to say,  Inches? or mm?

**Comment by HaykoKoryun** [comment]
How would that work?
Wouldn't you need to add some calibration system since 1 pixel isn't the same size on every screen, therefore it would be difficult to represent real world measurements.

Unless you want to superficially map pixels to metres, for example in game world building scenario where 1 pixel would represent 1cm.
