### ISSUE TITLE
How to create grid line for Particular div 

### ISSUE THREAD

**Issue by 27viveks** [mark-rolich/RulersGuides.js#16]
Hi Mark.,
        I working in your rulersguides.js. I create rulers for particular div refer <a href="http://jsfiddle.net/vivekkt91/y7976fvw/">FIDDLE</a>.but i need to create grid line for that particular div not in body element.How to achieved it? Can you give proper guidelines to complete this issues?

**Comment by mark-rolich** [comment]
Actually RulersGuides.js is not intended to be used in containers other than body, so I would think about placing it in an iframe.
If you really need to have it a in a  div, here are some adjustments needed:
1. Update getWindowSize, getScrollPos and getScrollSize functions to calculate container dimensions.
2. Instead of using vBound and hBound in mousedown handler you need to introduce vLowBound, vHighBound, etc., where container's left and top offsets will be taken in account.
3. Update removeInboundGuide accordingly in the same way.

Other than that, I think there'll be needed some changes in dom dimensions calculations, dialogs etc.

Here's an example [jsfiddle](http://jsfiddle.net/mrolich/r9bujj1q/9/).

**Comment by sushant357** [comment]
I saw the jsfiddle example its not working...
can you please help me out because i have same problem i want the ruler on my canvas element not on body part...

**Comment by kpomservices** [comment]
Updated jsfiddle. http://jsfiddle.net/r9bujj1q/21/
Its showing the guides and rulders now.
